### ISSUE TITLE
zoom issue

### ISSUE THREAD

**Issue by DanielRuf** [jbrewer/Responsive-Measure#1]
is there really no way in javascript to prevent these issues when you zoom in or out via browser shortcuts?

zooming out (opera win7 64bit, latest version) causes that it doesnt really zoom out

**Comment by wamatt** [comment]
Yeah the issue is it breaks usability, because effectively the user is now forced to have a certain font size. For example on my 27" Thunderbolt display, the font looks uncomfortably large.
